[project]
name = "livingspacetoolkit"
version = "1.9.5"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pyside6>=6.10.1",
    "pyyaml>=6.0.3",
    "ruff>=0.14.8",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.gui-scripts]
livingspacetoolkit = "livingspacetoolkit.main:main"